### ISSUE TITLE
Problem with zoom history in graphics with the new navigation toolbar

### ISSUE THREAD

**Issue by miguelmoreto** [miguelmoreto/labcontrole#20]
If you draw a graphic, like time domain simulation, that uses the new navigation toolbar, the zoom history does not work if you don't click on the graphic prior to apply zoom.
@andidevel do you have any idea of how to solve this?

**Comment by andidevel** [comment]
I'll check that.

**Comment by miguelmoreto** [comment]
Anderson it seens to be something related with windows. I've tested on linux and it worked.

**Comment by andidevel** [comment]
:+1: 

Sorry, but regarding to Windows, I can't help very much, I'm a Linux/Unix user only and I don't have a Windows machine laying around to test.

**Comment by miguelmoreto** [comment]
It seems something related with matplotlib. In the current version, this bug does not show anymore.
